### ISSUE TITLE
(node:5927) UnhandledPromiseRejectionWarning: MongoError: user is not allowed to do action [serverStatus] on [admin.]

### ISSUE THREAD

**Issue by simplenotezy** [qqilihq/mongoose-slugger#31]
I am getting this error:

    (node:5927) UnhandledPromiseRejectionWarning: MongoError: user is not allowed to do action [serverStatus] on [admin.]

Not sure why?

We're using atlas to host the mongodb

**Comment by qqilihq** [comment]
I have never used Atlas myself, so I cannot give any definite advice here. I would assume that the issue is happening here:

https://github.com/qqilihq/mongoose-slugger/blob/master/lib/slugger.ts#L218

https://github.com/qqilihq/mongoose-slugger/blob/master/lib/sluggerUtils.ts#L90

This checks that the proper storage engine is being used (it must be “Wired Tiger”), as otherwise the MongoDB errors cannot be properly parsed (as their messages might look different).

If Atlas uses Wired Tiger (which I’m not sure), it might make sense to either (a) introduce either a flag or (b) a dedicated check if the plugin is used for Atlas?
